### PR TITLE
Added margin to title to prevent overlap with the menu icon.

### PR DESCRIPTION
**Pull request by mlliou112**
Quick fix for #32

### CODE REVIEW

**Comment by dbtek** [comment]
Hi @mlliou112,

Thanks for the PR. I think there should be also a media query to target desktop screens.

**Comment by mlliou112** [comment]
I think screen size shouldn't actually affect this fix because the menu icon is in a fixed position 45 px from the right. I did however, up the margin to 70px because it clears the menu icon better.

Here's a picture of the 70px margin on 1440px wide screen, and 4k display.

image

image

**Comment by mlliou112** [comment]
I apologize, I misunderstood what you said. Hopefully this is better, I added the media query so the margin does not appear on smaller screens.

**Comment by dbtek** [comment]
Hi @mlliou112, no need to apologize. Thanks!

**Pull request merged**
